=== runnerty/runnerty/lib/schemas/chain.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["id", "name", "processes"],
  "properties": {
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "namespace": {
      "type": "string"
    },
    "execId": {
      "type": "string"
    },
    "queue": {
      "type": "string"
    },
    "priority": {
      "type": "number"
    },
    "input": {
      "type": ["array", "string"]
    },
    "custom_values": {
      "type": "object"
    },
    "retries": {
      "type": "number"
    },
    "retry_delay": {
      "type": ["number", "string"]
    },
    "iterable": {
      "type": "string",
      "enum": ["serie", "parallel"]
    },
    "ignore_on_concurrence": {
      "type": "boolean"
    },
    "abort_iteration_serie_on_error": {
      "type": "boolean"
    },
    "triggers": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "calendars": {
            "type": "object",
            "properties": {
              "allow": {
                "type": "string"
              },
              "disallow": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "depends_chains": {
      "anyOf": [
        {
          "type": "object",
          "properties": {
            "chain_id": {
              "type": "string"
            },
            "process_id": {
              "type": "string"
            }
          }
        },
        {
          "type": "array",
          "items": {
            "anyOf": [
              {
                "type": "object",
                "properties": {
                  "chain_id": {
                    "type": "string"
                  },
                  "process_id": {
                    "type": "string"
                  }
                }
              },
              {
                "type": "string"
              }
            ]
          }
        }
      ]
    },
    "notifications": {
      "type": "object",
      "properties": {
        "on_start": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["id"],
            "properties": {
              "id": {
                "type": "string"
              }
            }
          }
        },
        "on_end": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["id"],
            "properties": {
              "id": {
                "type": "string"
              }
            }
          }
        },
        "on_fail": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["id"],
            "properties": {
              "id": {
                "type": "string"
              }
            }
          }
        },
        "on_retry": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["id"],
            "properties": {
              "id": {
                "type": "string"
              }
            }
          }
        },
        "on_waiting_dependencies": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["id"],
            "properties": {
              "id": {
                "type": "string"
              }
            }
          }
        }
      }
    },
    "defaults_processes": {
      "type": "object",
      "properties": {
        "notifications": {
          "$ref": "processSchema#/definitions/notifications_process"
        },
        "chain_action_on_fail": {
          "$ref": "processSchema#/definitions/chain_action_on_fail_process"
        },
        "ignore_in_final_chain_status": {
          "type": "boolean"
        },
        "output": { "$ref": "processSchema#/definitions/output_process" }
      }
    },
    "processes": {
      "$ref": "processSchema"
    },
    "meta": {
      "type": "object",
      "properties": {
        "author": {
          "type": "string"
        },
        "team": {
          "type": "string"
        },
        "criticality": {
          "type": "string",
          "enum": ["low", "medium", "high"]
        },
        "contacts": {
          "type": "array",
          "items": {
            "type": "object",
            "required": ["name"],
            "properties": {
              "name": {
                "type": "string"
              },
              "email": {
                "type": "string"
              },
              "phone": {
                "type": "string"
              }
            }
          }
        },
        "fail_comments": {
          "type": "string"
        },
        "relaunchable": {
          "type": "boolean"
        },
        "input_keys": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "keywords": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "max_expected_time": {
          "type": "string"
        }
      }
    },
    "runnerty.io": {
      "type": "object",
      "properties": {
        "remoteControl": {
          "type": "boolean"
        },
        "sync": {
          "type": "object",
          "properties": {
            "events": {
              "type": "boolean"
            },
            "chain": {
              "type": "boolean"
            }
          }
        }
      }
    }
  }
}

=== runnerty/runnerty/lib/cli/base/chains/chain-one.json
{
  "$schema": "https://raw.githubusercontent.com/runnerty/schemas/master/schemas/3.5/chain.json",
  "id": "CHAIN_ONE",
  "name": "Chain one sample",
  "triggers": [
    {
      "id": "schedule_default",
      "schedule_interval": "*/1 * * * *"
    }
  ],
  "processes": [
    {
      "id": "PROCESS_ONE",
      "name": "Proccess One",
      "exec": {
        "id": "shell_default",
        "command": "echo hello world!"
      }
    }
  ]
}

=== runnerty/runnerty/__tests__/end2end/plan_link_chain_sample.json
{
  "id": "CHAIN_OF_PLAN_LINK",
  "name": "CHAIN_OF_PLAN_LINK",
  "defaults_processes": {
    "notifications": {
      "on_start": [
        {
          "id": "console_default",
          "message": "[[DP]]! PROCESS @GV(PROCESS_ID) START - TS:@GV(TEST_NUMBER)"
        }
      ],
      "on_retry": [
        {
          "id": "console_default",
          "message": "[[DP]]! RETRY PROCESS @GV(PROCESS_ID): @GV(PROCESS_EXEC_ERR_OUTPUT) - TS:@GV(TEST_NUMBER)"
        }
      ],
      "on_fail": [
        {
          "id": "console_default",
          "message": "[[DP]]! ERR! PROCESS @GV(PROCESS_ID) FAIL: @GV(PROCESS_EXEC_ERR_OUTPUT)"
        }
      ],
      "on_end": [
        {
          "id": "console_default",
          "message": "[[DP]]! PROCESS @GV(PROCESS_ID) END - TS:@GV(TEST_NUMBER)"
        }
      ]
    },
    "chain_action_on_fail": "abort"
  },
  "notifications": {
    "on_start": [
      {
        "id": "console_default",
        "message": "CHAIN @GV(CHAIN_ID) START"
      }
    ],
    "on_end": [
      {
        "id": "console_default",
        "message": "CHAIN @GV(CHAIN_ID) END"
      }
    ],
    "on_fail": [
      {
        "id": "console_default",
        "message": "CHAIN @GV(CHAIN_ID) FAIL"
      }
    ]
  },
  "processes": [
    {
      "id": "PROCESS_ONE",
      "name": "PROCESS_ONE",
      "exec": {
        "id": "shell_default",
        "command": "sleep 0.2 && echo TEST"
      },
      "output_share": [
        {
          "key": "TEST",
          "name": "NUMBER",
          "value": "@GV(PROCESS_EXEC_MSG_OUTPUT)"
        }
      ]
    }
  ]
}
